package adaevomodel.designtime.systemextraction.pcm;

import adaevomodel.designtime.systemextraction.pcm.data.ConnectionConflict;
import adaevomodel.designtime.systemextraction.pcm.impl.PCMSystemBuilder;

/**
 * Listener for conflicts that are generated by the {@link PCMSystemBuilder}
 * when there are mutliple components available for the same required role.
 * 
 * @author David Monschein
 *
 */
public interface IConnectionConflictListener {

	/**
	 * Called when a conflict occurs.
	 * 
	 * @param conflict the conflict
	 */
	public void conflict(ConnectionConflict conflict);

}
